// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFurIIU5U3jZwdMVNktXRc5VfpYP1seqk',
    appId: '1:229908514681:web:0af459ada857a3189c91a8',
    messagingSenderId: '229908514681',
    projectId: 'parkavail-9f48f',
    authDomain: 'parkavail-9f48f.firebaseapp.com',
    storageBucket: 'parkavail-9f48f.firebasestorage.app',
    measurementId: 'G-GWCJ9YSKS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
<<<<<<< HEAD
    apiKey: 'AIzaSyCuL_AflqLVpk4G4OmmIbULm-W_nqp7pPM',
    appId: '1:133102442404:android:9fc5eb72126a55aaa3d331',
    messagingSenderId: '133102442404',
    projectId: 'parkavail-3c32c',
    storageBucket: 'parkavail-3c32c.firebasestorage.app',
=======
    apiKey: 'AIzaSyDm8xMi_uVi4KY0FYf9fVez9p-LVJttews',
    appId: '1:229908514681:android:a7d9fe3abbbd2cc69c91a8',
    messagingSenderId: '229908514681',
    projectId: 'parkavail-9f48f',
    storageBucket: 'parkavail-9f48f.firebasestorage.app',
>>>>>>> 036b57e0e3b6b646c3710d1fd6ed73cbaec7d65c
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMnNvcRXnHaV6Ch3xRQWOqQ15DXY_LVR8',
    appId: '1:229908514681:ios:70a0c0b39a0256cf9c91a8',
    messagingSenderId: '229908514681',
    projectId: 'parkavail-9f48f',
    storageBucket: 'parkavail-9f48f.firebasestorage.app',
<<<<<<< HEAD
    androidClientId: '229908514681-97d3seiqaf5l9lkn7kad5vncv666svul.apps.googleusercontent.com',
    iosClientId: '229908514681-hg0t6ob97gmk3qtckv75k2kjvj061jfh.apps.googleusercontent.com',
=======
>>>>>>> 036b57e0e3b6b646c3710d1fd6ed73cbaec7d65c
    iosBundleId: 'com.example.bookMyPark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMnNvcRXnHaV6Ch3xRQWOqQ15DXY_LVR8',
    appId: '1:229908514681:ios:70a0c0b39a0256cf9c91a8',
    messagingSenderId: '229908514681',
    projectId: 'parkavail-9f48f',
    storageBucket: 'parkavail-9f48f.firebasestorage.app',
<<<<<<< HEAD
    androidClientId: '229908514681-97d3seiqaf5l9lkn7kad5vncv666svul.apps.googleusercontent.com',
    iosClientId: '229908514681-hg0t6ob97gmk3qtckv75k2kjvj061jfh.apps.googleusercontent.com',
=======
>>>>>>> 036b57e0e3b6b646c3710d1fd6ed73cbaec7d65c
    iosBundleId: 'com.example.bookMyPark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFurIIU5U3jZwdMVNktXRc5VfpYP1seqk',
    appId: '1:229908514681:web:ca94e35d44ec21449c91a8',
    messagingSenderId: '229908514681',
    projectId: 'parkavail-9f48f',
    authDomain: 'parkavail-9f48f.firebaseapp.com',
    storageBucket: 'parkavail-9f48f.firebasestorage.app',
    measurementId: 'G-8D94WN1MYB',
  );

}